title: Haoqian Li's Homepage
page-top-title: Haoqian Li
top-section-bg-text: 
home-subtitle: Haoqian Li&ensp;|&ensp;李昊谦
copyright-text: '&copy; Haoqian Li 2026; Ref. Sen Li 2023-2026. All Rights Reserved.'
